site_name: Scripta Compiler Docs
site_url: https://jxxcarlson.github.io/docs-scripta-compiler
docs_dir: 'docs-scripta-compiler'

theme: readthedocs

nav:
  - Home: 'index.md'
  - 'introduction.md'
  - 'overview.md'
  - 'dataStructures.md'
  - 'common-code.md'
  - 'synchronization.md'
  - 'render.md'
  - 'l0.md'
  - 'lx.md'