site_name: Scripta Compiler Docs
site_url: https://jxxcarlson.github.io/docs-scripta-compiler
docs_dir: 'docs-scripta-compiler'

theme: readthedocs


nav:
  - Home: 'index.md'
  - Introduction: 'introduction.md'
  - Overview: 'overview.md'
  - Data structures: 'dataStructures.md'
  - Common code: 'common-code.md'
  - Differential Parser: 'differential-parser.md'
  - Synchronization: 'syncrhonization.md'
  - L0 Parser: 'l0-parser.md'
  - MicroLaTeX Parser: 'lx-parser.md'
  - Rendering: 'render.md'
  - Mkdocs: 'mkdocs.md'